/*表头信息*/
DELETE PPITEM WHERE PPITEM_XXJDM = 'CMSCZJH'
go
INSERT INTO PPITEM(PPITEM_XXJDM,PPITEM_DM,PPITEM_MC,PPITEM_YHMC,PPITEM_SFZDY,PPITEM_DESCRIBE,PPITEM_XH,PPITEM_ZDLX,PPITEM_SJCD,PPITEM_XSCD,PPITEM_SFZJ,PPITEM_SFWY,PPITEM_SFWK,PPITEM_SFXT,PPITEM_DEFAULT,PPITEM_SFKY,PPITEM_CJZ,PPITEM_CJRQ,PPITEM_GXRQ,PPITEM_LRFS,PPITEM_BYGS,PPITEM_LRDX,PPITEM_SFDY,PPITEM_SFXS,PPITEM_GLXXX,PPITEM_QYBZ,PPITEM_SJQX)
 VALUES ('CMSCZJH','CMSCZJH_JHLS','流水','流水',null,null,1,'NM',10,0,0,0,0,1,'',1,null,null,null,1,null,null,0,1,null,1,null)
go
INSERT INTO PPITEM(PPITEM_XXJDM,PPITEM_DM,PPITEM_MC,PPITEM_YHMC,PPITEM_SFZDY,PPITEM_DESCRIBE,PPITEM_XH,PPITEM_ZDLX,PPITEM_SJCD,PPITEM_XSCD,PPITEM_SFZJ,PPITEM_SFWY,PPITEM_SFWK,PPITEM_SFXT,PPITEM_DEFAULT,PPITEM_SFKY,PPITEM_CJZ,PPITEM_CJRQ,PPITEM_GXRQ,PPITEM_LRFS,PPITEM_BYGS,PPITEM_LRDX,PPITEM_SFDY,PPITEM_SFXS,PPITEM_GLXXX,PPITEM_QYBZ,PPITEM_SJQX)
 VALUES ('CMSCZJH','CMSCZJH_JHBH','编号','编号',null,null,2,'NVARCHAR',20,0,0,0,0,1,'',1,null,null,null,1,null,null,0,1,null,1,null)
go
INSERT INTO PPITEM(PPITEM_XXJDM,PPITEM_DM,PPITEM_MC,PPITEM_YHMC,PPITEM_SFZDY,PPITEM_DESCRIBE,PPITEM_XH,PPITEM_ZDLX,PPITEM_SJCD,PPITEM_XSCD,PPITEM_SFZJ,PPITEM_SFWY,PPITEM_SFWK,PPITEM_SFXT,PPITEM_DEFAULT,PPITEM_SFKY,PPITEM_CJZ,PPITEM_CJRQ,PPITEM_GXRQ,PPITEM_LRFS,PPITEM_BYGS,PPITEM_LRDX,PPITEM_SFDY,PPITEM_SFXS,PPITEM_GLXXX,PPITEM_QYBZ,PPITEM_SJQX)
 VALUES ('CMSCZJH','CMSCZJH_BZRY','人员','人员',null,null,3,'NVARCHAR',50,0,0,0,0,1,'',1,null,null,null,1,null,null,0,1,null,1,null)
go
INSERT INTO PPITEM(PPITEM_XXJDM,PPITEM_DM,PPITEM_MC,PPITEM_YHMC,PPITEM_SFZDY,PPITEM_DESCRIBE,PPITEM_XH,PPITEM_ZDLX,PPITEM_SJCD,PPITEM_XSCD,PPITEM_SFZJ,PPITEM_SFWY,PPITEM_SFWK,PPITEM_SFXT,PPITEM_DEFAULT,PPITEM_SFKY,PPITEM_CJZ,PPITEM_CJRQ,PPITEM_GXRQ,PPITEM_LRFS,PPITEM_BYGS,PPITEM_LRDX,PPITEM_SFDY,PPITEM_SFXS,PPITEM_GLXXX,PPITEM_QYBZ,PPITEM_SJQX)
 VALUES ('CMSCZJH','CMSCZJH_BZRQ','日期','日期',null,null,4,'NVARCHAR',8,0,0,0,0,1,'',1,null,null,null,1,null,null,0,1,null,1,null)
go
/*表体信息*/
DELETE PPITEM WHERE PPITEM_XXJDM = 'CMSCZJHMX'
go
INSERT INTO PPITEM(PPITEM_XXJDM,PPITEM_DM,PPITEM_MC,PPITEM_YHMC,PPITEM_SFZDY,PPITEM_DESCRIBE,PPITEM_XH,PPITEM_ZDLX,PPITEM_SJCD,PPITEM_XSCD,PPITEM_SFZJ,PPITEM_SFWY,PPITEM_SFWK,PPITEM_SFXT,PPITEM_DEFAULT,PPITEM_SFKY,PPITEM_CJZ,PPITEM_CJRQ,PPITEM_GXRQ,PPITEM_LRFS,PPITEM_BYGS,PPITEM_LRDX,PPITEM_SFDY,PPITEM_SFXS,PPITEM_GLXXX,PPITEM_QYBZ,PPITEM_SJQX)
 VALUES ('CMSCZJHMX','CMSCZJH_JHLS','流水','流水',null,null,1,'NM',10,0,0,0,0,1,'',1,null,null,null,1,null,null,0,1,null,1,null)
go
INSERT INTO PPITEM(PPITEM_XXJDM,PPITEM_DM,PPITEM_MC,PPITEM_YHMC,PPITEM_SFZDY,PPITEM_DESCRIBE,PPITEM_XH,PPITEM_ZDLX,PPITEM_SJCD,PPITEM_XSCD,PPITEM_SFZJ,PPITEM_SFWY,PPITEM_SFWK,PPITEM_SFXT,PPITEM_DEFAULT,PPITEM_SFKY,PPITEM_CJZ,PPITEM_CJRQ,PPITEM_GXRQ,PPITEM_LRFS,PPITEM_BYGS,PPITEM_LRDX,PPITEM_SFDY,PPITEM_SFXS,PPITEM_GLXXX,PPITEM_QYBZ,PPITEM_SJQX)
 VALUES ('CMSCZJHMX','CMSCZJH_JHBH','编号','编号',null,null,2,'NVARCHAR',20,0,0,0,0,1,'',1,null,null,null,1,null,null,0,1,null,1,null)
go
INSERT INTO PPITEM(PPITEM_XXJDM,PPITEM_DM,PPITEM_MC,PPITEM_YHMC,PPITEM_SFZDY,PPITEM_DESCRIBE,PPITEM_XH,PPITEM_ZDLX,PPITEM_SJCD,PPITEM_XSCD,PPITEM_SFZJ,PPITEM_SFWY,PPITEM_SFWK,PPITEM_SFXT,PPITEM_DEFAULT,PPITEM_SFKY,PPITEM_CJZ,PPITEM_CJRQ,PPITEM_GXRQ,PPITEM_LRFS,PPITEM_BYGS,PPITEM_LRDX,PPITEM_SFDY,PPITEM_SFXS,PPITEM_GLXXX,PPITEM_QYBZ,PPITEM_SJQX)
 VALUES ('CMSCZJHMX','CMSCZJH_BZRY','人员','人员',null,null,3,'NVARCHAR',50,0,0,0,0,1,'',1,null,null,null,1,null,null,0,1,null,1,null)
go
INSERT INTO PPITEM(PPITEM_XXJDM,PPITEM_DM,PPITEM_MC,PPITEM_YHMC,PPITEM_SFZDY,PPITEM_DESCRIBE,PPITEM_XH,PPITEM_ZDLX,PPITEM_SJCD,PPITEM_XSCD,PPITEM_SFZJ,PPITEM_SFWY,PPITEM_SFWK,PPITEM_SFXT,PPITEM_DEFAULT,PPITEM_SFKY,PPITEM_CJZ,PPITEM_CJRQ,PPITEM_GXRQ,PPITEM_LRFS,PPITEM_BYGS,PPITEM_LRDX,PPITEM_SFDY,PPITEM_SFXS,PPITEM_GLXXX,PPITEM_QYBZ,PPITEM_SJQX)
 VALUES ('CMSCZJHMX','CMSCZJH_BZRQ','日期','日期',null,null,4,'NVARCHAR',8,0,0,0,0,1,'',1,null,null,null,1,null,null,0,1,null,1,null)
go